/* Generated by Pyrex 0.9.2.1 on Thu Jan 13 13:15:52 2005 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "stdio.h"
#include "standard_model_helper.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void **vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

/* Declarations from standard_model */

staticforward PyTypeObject __pyx_type_14standard_model_StandardModel;

struct __pyx_obj_14standard_model_StandardModel {
  PyObject_HEAD
  struct __pyx_vtabstruct_14standard_model_StandardModel *__pyx_vtab;
  int order;
  int radix;
  double (*scores);
  int scores_len;
};

struct __pyx_vtabstruct_14standard_model_StandardModel {
  PyObject *((*init)(struct __pyx_obj_14standard_model_StandardModel *,int ,int ,double (*)));
};
static struct __pyx_vtabstruct_14standard_model_StandardModel *__pyx_vtabptr_14standard_model_StandardModel;

static PyTypeObject *__pyx_ptype_14standard_model_StandardModel = 0;
static PyObject *(__pyx_f_14standard_model_fill_in(int ,int ,int (*(*)),PyObject *)); /*proto*/

/* Implementation of standard_model */


static PyObject *__pyx_n_sys;
static PyObject *__pyx_n_array;
static PyObject *__pyx_n_from_file;
static PyObject *__pyx_n_train;

static PyObject *__pyx_f_14standard_model_13StandardModel_init(struct __pyx_obj_14standard_model_StandardModel *__pyx_v_self,int __pyx_v_order,int __pyx_v_radix,double (*__pyx_v_scores)) {
  PyObject *__pyx_r;
  extern double pow(double, double);
  Py_INCREF(__pyx_v_self);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":31 */
  __pyx_v_self->order = __pyx_v_order;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":32 */
  __pyx_v_self->radix = __pyx_v_radix;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":33 */
  __pyx_v_self->scores = __pyx_v_scores;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":34 */
  __pyx_v_self->scores_len = pow(__pyx_v_radix, (__pyx_v_order + 1));

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("standard_model.StandardModel.init");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_14standard_model_13StandardModel_get_order(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14standard_model_13StandardModel_get_order(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":37 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->order); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("standard_model.StandardModel.get_order");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_14standard_model_13StandardModel_get_radix(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14standard_model_13StandardModel_get_radix(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":40 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->radix); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("standard_model.StandardModel.get_radix");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_d;
static PyObject *__pyx_n_append;


static PyObject *__pyx_f_14standard_model_13StandardModel_get_scores(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14standard_model_13StandardModel_get_scores(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_a;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  long __pyx_4;
  int __pyx_5;
  int __pyx_6;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_a = Py_None; Py_INCREF(__pyx_v_a);
  __pyx_v_i = Py_None; Py_INCREF(__pyx_v_i);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":43 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_array); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_INCREF(__pyx_n_d);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_n_d);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_a);
  __pyx_v_a = __pyx_3;
  __pyx_3 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":44 */
  __pyx_5 = ((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->scores_len;
  for (__pyx_4 = 0; __pyx_4 < __pyx_5; ++__pyx_4) {
    __pyx_1 = PyInt_FromLong(__pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_1;
    __pyx_1 = 0;

    /* "/home/james/work/py_rp/rp/standard_model.pyx":45 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_a, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    __pyx_6 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    __pyx_3 = PyFloat_FromDouble((((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->scores[__pyx_6])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":46 */
  Py_INCREF(__pyx_v_a);
  __pyx_r = __pyx_v_a;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("standard_model.StandardModel.get_scores");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_a);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k5p;

char (__pyx_k5[]) = "No valid data in region to be scored";

static PyObject *__pyx_f_14standard_model_13StandardModel_score(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14standard_model_13StandardModel_score(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_string = 0;
  int __pyx_v_start;
  int __pyx_v_length;
  int (*__pyx_v_buf);
  int __pyx_v_buf_len;
  double __pyx_v_rval;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"string","start","length",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "Oii", __pyx_argnames, &__pyx_v_string, &__pyx_v_start, &__pyx_v_length)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_string);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":52 */
  __pyx_1 = PyObject_AsReadBuffer(__pyx_v_string,((void (*(*)))(&__pyx_v_buf)),(&__pyx_v_buf_len)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}

  /* "/home/james/work/py_rp/rp/standard_model.pyx":53 */
  if (!((__pyx_v_start + __pyx_v_length) <= (__pyx_v_buf_len / (sizeof(int ))))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
  }

  /* "/home/james/work/py_rp/rp/standard_model.pyx":54 */
  __pyx_1 = score_string(((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->order,((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->radix,((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->scores,__pyx_v_buf,__pyx_v_start,__pyx_v_length,(&__pyx_v_rval));
  if (__pyx_1) {

    /* "/home/james/work/py_rp/rp/standard_model.pyx":55 */
    __pyx_2 = PyFloat_FromDouble(__pyx_v_rval); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/james/work/py_rp/rp/standard_model.pyx":57 */
    __Pyx_Raise(__pyx_k5p, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("standard_model.StandardModel.score");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_string);
  return __pyx_r;
}

static PyObject *__pyx_n_write;
static PyObject *__pyx_n_str;

static PyObject *__pyx_k6p;
static PyObject *__pyx_k7p;
static PyObject *__pyx_k8p;
static PyObject *__pyx_k9p;
static PyObject *__pyx_k10p;

char (__pyx_k6[]) = "order: ";
char (__pyx_k7[]) = "\n";
char (__pyx_k8[]) = "radix: ";
char (__pyx_k9[]) = "\n";
char (__pyx_k10[]) = "\n";

static PyObject *__pyx_f_14standard_model_13StandardModel_to_file(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14standard_model_13StandardModel_to_file(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_file = 0;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  long __pyx_5;
  int __pyx_6;
  int __pyx_7;
  static char *__pyx_argnames[] = {"file",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_file)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_file);
  __pyx_v_i = Py_None; Py_INCREF(__pyx_v_i);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":60 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_file, __pyx_n_write); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_str); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->order); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_2 = PyNumber_Add(__pyx_k6p, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyNumber_Add(__pyx_2, __pyx_k7p); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":61 */
  __pyx_4 = PyObject_GetAttr(__pyx_v_file, __pyx_n_write); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_str); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->radix); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyNumber_Add(__pyx_k8p, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyNumber_Add(__pyx_1, __pyx_k9p); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":62 */
  __pyx_6 = ((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->scores_len;
  for (__pyx_5 = 0; __pyx_5 < __pyx_6; ++__pyx_5) {
    __pyx_2 = PyInt_FromLong(__pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_2;
    __pyx_2 = 0;

    /* "/home/james/work/py_rp/rp/standard_model.pyx":63 */
    __pyx_4 = PyObject_GetAttr(__pyx_v_file, __pyx_n_write); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_str); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_7 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_1 = PyFloat_FromDouble((((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->scores[__pyx_7])); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
    __pyx_1 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyNumber_Add(__pyx_1, __pyx_k10p); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_4, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_L2:;
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("standard_model.StandardModel.to_file");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_file);
  return __pyx_r;
}

static void __pyx_f_14standard_model_13StandardModel___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_14standard_model_13StandardModel___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":66 */
  free_scores(((struct __pyx_obj_14standard_model_StandardModel *)__pyx_v_self)->scores);

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("standard_model.StandardModel.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_n_next;
static PyObject *__pyx_n_split;
static PyObject *__pyx_n_int;
static PyObject *__pyx_n_float;

static PyObject *__pyx_k11p;
static PyObject *__pyx_k12p;
static PyObject *__pyx_k13p;
static PyObject *__pyx_k14p;

char (__pyx_k11[]) = "order:";
char (__pyx_k12[]) = "Expected 'order:'";
char (__pyx_k13[]) = "radix:";
char (__pyx_k14[]) = "Expected 'radix:'";

static PyObject *__pyx_f_14standard_model_from_file(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14standard_model_from_file(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_f = 0;
  int __pyx_v_order;
  int __pyx_v_size;
  int __pyx_v_radix;
  double (*__pyx_v_scores);
  struct __pyx_obj_14standard_model_StandardModel *__pyx_v_rval;
  PyObject *__pyx_v_fields;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  long __pyx_5;
  PyObject *__pyx_6 = 0;
  double __pyx_7;
  static char *__pyx_argnames[] = {"f",0};
  extern double pow(double, double);
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_f)) return 0;
  Py_INCREF(__pyx_v_f);
  ((PyObject*)__pyx_v_rval) = Py_None; Py_INCREF(((PyObject*)__pyx_v_rval));
  __pyx_v_fields = Py_None; Py_INCREF(__pyx_v_fields);
  __pyx_v_i = Py_None; Py_INCREF(__pyx_v_i);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":75 */
  /*try:*/ {

    /* "/home/james/work/py_rp/rp/standard_model.pyx":76 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_f, __pyx_n_next); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L2;}
    __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L2;}
    __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyObject_GetAttr(__pyx_3, __pyx_n_split); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L2;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L2;}
    __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_v_fields);
    __pyx_v_fields = __pyx_3;
    __pyx_3 = 0;

    /* "/home/james/work/py_rp/rp/standard_model.pyx":77 */
    __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L2;}
    __pyx_2 = PyObject_GetItem(__pyx_v_fields, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (PyObject_Cmp(__pyx_2, __pyx_k11p, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L2;}
    __pyx_4 = __pyx_4 == 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (!__pyx_4) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L2;}
    }

    /* "/home/james/work/py_rp/rp/standard_model.pyx":78 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_int); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L2;}
    __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L2;}
    __pyx_2 = PyObject_GetItem(__pyx_v_fields, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L2;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L2;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_4 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L2;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_order = __pyx_4;
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_XDECREF(__pyx_3); __pyx_3 = 0;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":79 */
  /*except:*/ {
    __Pyx_AddTraceback("standard_model.from_file");
    __pyx_3 = __Pyx_GetExcValue(); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/james/work/py_rp/rp/standard_model.pyx":80 */
    __Pyx_Raise(__pyx_k12p, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":82 */
  /*try:*/ {

    /* "/home/james/work/py_rp/rp/standard_model.pyx":83 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_f, __pyx_n_next); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L4;}
    __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L4;}
    __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L4;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyObject_GetAttr(__pyx_3, __pyx_n_split); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L4;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L4;}
    __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L4;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_v_fields);
    __pyx_v_fields = __pyx_3;
    __pyx_3 = 0;

    /* "/home/james/work/py_rp/rp/standard_model.pyx":84 */
    __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L4;}
    __pyx_2 = PyObject_GetItem(__pyx_v_fields, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L4;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (PyObject_Cmp(__pyx_2, __pyx_k13p, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L4;}
    __pyx_4 = __pyx_4 == 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (!__pyx_4) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L4;}
    }

    /* "/home/james/work/py_rp/rp/standard_model.pyx":85 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_int); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L4;}
    __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L4;}
    __pyx_2 = PyObject_GetItem(__pyx_v_fields, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L4;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L4;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L4;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_4 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L4;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_radix = __pyx_4;
  }
  goto __pyx_L5;
  __pyx_L4:;
  Py_XDECREF(__pyx_3); __pyx_3 = 0;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":86 */
  /*except:*/ {
    __Pyx_AddTraceback("standard_model.from_file");
    __pyx_3 = __Pyx_GetExcValue(); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/james/work/py_rp/rp/standard_model.pyx":87 */
    __Pyx_Raise(__pyx_k14p, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":89 */
  __pyx_v_size = pow(__pyx_v_radix, (__pyx_v_order + 1));

  /* "/home/james/work/py_rp/rp/standard_model.pyx":90 */
  __pyx_v_scores = new_real_array(__pyx_v_size);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":91 */
  for (__pyx_5 = 0; __pyx_5 < __pyx_v_size; ++__pyx_5) {
    __pyx_1 = PyInt_FromLong(__pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_1;
    __pyx_1 = 0;

    /* "/home/james/work/py_rp/rp/standard_model.pyx":92 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_float); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_v_f, __pyx_n_next); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    __pyx_6 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_6);
    __pyx_6 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_7 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_4 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    (__pyx_v_scores[__pyx_4]) = __pyx_7;
    __pyx_L6:;
  }
  __pyx_L7:;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":94 */
  __pyx_6 = PyTuple_New(0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(((PyObject*)__pyx_ptype_14standard_model_StandardModel), __pyx_6); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_14standard_model_StandardModel)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_rval));
  ((PyObject *)__pyx_v_rval) = __pyx_2;
  __pyx_2 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":95 */
  __pyx_3 = ((struct __pyx_vtabstruct_14standard_model_StandardModel *)__pyx_v_rval->__pyx_vtab)->init(__pyx_v_rval,__pyx_v_order,__pyx_v_radix,__pyx_v_scores); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":96 */
  Py_INCREF(((PyObject *)__pyx_v_rval));
  __pyx_r = ((PyObject *)__pyx_v_rval);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("standard_model.from_file");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rval);
  Py_DECREF(__pyx_v_fields);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_f);
  return __pyx_r;
}

static PyObject *__pyx_f_14standard_model_train(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14standard_model_train(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_order;
  int __pyx_v_radix;
  PyObject *__pyx_v_pos_strings = 0;
  PyObject *__pyx_v_neg_strings = 0;
  int (*(*__pyx_v_pos_counts));
  int (*(*__pyx_v_neg_counts));
  double (*(*__pyx_v_pos_probs));
  double (*(*__pyx_v_neg_probs));
  double (*__pyx_v_scores);
  struct __pyx_obj_14standard_model_StandardModel *__pyx_v_rval;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"order","radix","pos_strings","neg_strings",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "iiOO", __pyx_argnames, &__pyx_v_order, &__pyx_v_radix, &__pyx_v_pos_strings, &__pyx_v_neg_strings)) return 0;
  Py_INCREF(__pyx_v_pos_strings);
  Py_INCREF(__pyx_v_neg_strings);
  ((PyObject*)__pyx_v_rval) = Py_None; Py_INCREF(((PyObject*)__pyx_v_rval));

  /* "/home/james/work/py_rp/rp/standard_model.pyx":110 */
  __pyx_v_pos_counts = new_counts(__pyx_v_order,__pyx_v_radix);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":111 */
  __pyx_v_neg_counts = new_counts(__pyx_v_order,__pyx_v_radix);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":113 */
  __pyx_1 = __pyx_f_14standard_model_fill_in(__pyx_v_order,__pyx_v_radix,__pyx_v_pos_counts,__pyx_v_pos_strings); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":114 */
  __pyx_1 = __pyx_f_14standard_model_fill_in(__pyx_v_order,__pyx_v_radix,__pyx_v_neg_counts,__pyx_v_neg_strings); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":116 */
  __pyx_v_pos_probs = counts_to_probs(__pyx_v_order,__pyx_v_radix,__pyx_v_pos_counts);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":117 */
  __pyx_v_neg_probs = counts_to_probs(__pyx_v_order,__pyx_v_radix,__pyx_v_neg_counts);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":119 */
  free_counts(__pyx_v_pos_counts,__pyx_v_order);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":120 */
  free_counts(__pyx_v_neg_counts,__pyx_v_order);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":122 */
  __pyx_v_scores = probs_to_score_matrix(__pyx_v_order,__pyx_v_radix,__pyx_v_pos_probs,__pyx_v_neg_probs);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":124 */
  free_probs(__pyx_v_pos_probs,__pyx_v_order);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":125 */
  free_probs(__pyx_v_neg_probs,__pyx_v_order);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":127 */
  __pyx_1 = PyTuple_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(((PyObject*)__pyx_ptype_14standard_model_StandardModel), __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_2, __pyx_ptype_14standard_model_StandardModel)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_rval));
  ((PyObject *)__pyx_v_rval) = __pyx_2;
  __pyx_2 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":128 */
  __pyx_1 = ((struct __pyx_vtabstruct_14standard_model_StandardModel *)__pyx_v_rval->__pyx_vtab)->init(__pyx_v_rval,__pyx_v_order,__pyx_v_radix,__pyx_v_scores); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":130 */
  Py_INCREF(((PyObject *)__pyx_v_rval));
  __pyx_r = ((PyObject *)__pyx_v_rval);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("standard_model.train");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rval);
  Py_DECREF(__pyx_v_pos_strings);
  Py_DECREF(__pyx_v_neg_strings);
  return __pyx_r;
}

static PyObject *__pyx_f_14standard_model_fill_in(int __pyx_v_order,int __pyx_v_radix,int (*(*__pyx_v_counts)),PyObject *__pyx_v_strings) {
  int (*__pyx_v_buf);
  int __pyx_v_buf_len;
  PyObject *__pyx_v_string;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  Py_INCREF(__pyx_v_strings);
  __pyx_v_string = Py_None; Py_INCREF(__pyx_v_string);

  /* "/home/james/work/py_rp/rp/standard_model.pyx":135 */
  __pyx_1 = PyObject_GetIter(__pyx_v_strings); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  for (;;) {
    __pyx_L2:;
    __pyx_2 = PyIter_Next(__pyx_1);
    if (!__pyx_2) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_string);
    __pyx_v_string = __pyx_2;
    __pyx_2 = 0;

    /* "/home/james/work/py_rp/rp/standard_model.pyx":136 */
    __pyx_3 = PyObject_AsReadBuffer(__pyx_v_string,((void (*(*)))(&__pyx_v_buf)),(&__pyx_v_buf_len)); if (__pyx_3 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}

    /* "/home/james/work/py_rp/rp/standard_model.pyx":137 */
    fill_in_counts(__pyx_v_order,__pyx_v_radix,__pyx_v_counts,__pyx_v_buf,(__pyx_v_buf_len / (sizeof(int ))));
  }
  __pyx_L3:;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("standard_model.fill_in");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_string);
  Py_DECREF(__pyx_v_strings);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_append, "append"},
  {&__pyx_n_array, "array"},
  {&__pyx_n_d, "d"},
  {&__pyx_n_float, "float"},
  {&__pyx_n_from_file, "from_file"},
  {&__pyx_n_int, "int"},
  {&__pyx_n_next, "next"},
  {&__pyx_n_split, "split"},
  {&__pyx_n_str, "str"},
  {&__pyx_n_sys, "sys"},
  {&__pyx_n_train, "train"},
  {&__pyx_n_write, "write"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k5p, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k7p, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k8p, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k9p, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k10p, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k11p, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k12p, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k13p, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_k14p, __pyx_k14, sizeof(__pyx_k14)},
  {0, 0, 0}
};
static struct __pyx_vtabstruct_14standard_model_StandardModel __pyx_vtable_14standard_model_StandardModel;

static PyObject *__pyx_tp_new_14standard_model_StandardModel(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_14standard_model_StandardModel *p = (struct __pyx_obj_14standard_model_StandardModel *)o;
  (struct __pyx_vtabstruct_14standard_model_StandardModel *)p->__pyx_vtab = __pyx_vtabptr_14standard_model_StandardModel;
  return o;
}

static void __pyx_tp_dealloc_14standard_model_StandardModel(PyObject *o) {
  struct __pyx_obj_14standard_model_StandardModel *p = (struct __pyx_obj_14standard_model_StandardModel *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_14standard_model_13StandardModel___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_14standard_model_StandardModel(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_14standard_model_StandardModel *p = (struct __pyx_obj_14standard_model_StandardModel *)o;
  return 0;
}

static int __pyx_tp_clear_14standard_model_StandardModel(PyObject *o) {
  struct __pyx_obj_14standard_model_StandardModel *p = (struct __pyx_obj_14standard_model_StandardModel *)o;
  return 0;
}

static struct PyMethodDef __pyx_methods_14standard_model_StandardModel[] = {
  {"get_order", (PyCFunction)__pyx_f_14standard_model_13StandardModel_get_order, METH_VARARGS|METH_KEYWORDS, 0},
  {"get_radix", (PyCFunction)__pyx_f_14standard_model_13StandardModel_get_radix, METH_VARARGS|METH_KEYWORDS, 0},
  {"get_scores", (PyCFunction)__pyx_f_14standard_model_13StandardModel_get_scores, METH_VARARGS|METH_KEYWORDS, 0},
  {"score", (PyCFunction)__pyx_f_14standard_model_13StandardModel_score, METH_VARARGS|METH_KEYWORDS, 0},
  {"to_file", (PyCFunction)__pyx_f_14standard_model_13StandardModel_to_file, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_StandardModel = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_StandardModel = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_StandardModel = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_StandardModel = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_14standard_model_StandardModel = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "standard_model.StandardModel", /*tp_name*/
  sizeof(struct __pyx_obj_14standard_model_StandardModel), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_14standard_model_StandardModel, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_StandardModel, /*tp_as_number*/
  &__pyx_tp_as_sequence_StandardModel, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_StandardModel, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_StandardModel, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_14standard_model_StandardModel, /*tp_traverse*/
  __pyx_tp_clear_14standard_model_StandardModel, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_14standard_model_StandardModel, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_14standard_model_StandardModel, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"from_file", (PyCFunction)__pyx_f_14standard_model_from_file, METH_VARARGS|METH_KEYWORDS, 0},
  {"train", (PyCFunction)__pyx_f_14standard_model_train, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

DL_EXPORT(void) initstandard_model(void); /*proto*/
DL_EXPORT(void) initstandard_model(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_m = Py_InitModule4("standard_model", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_vtabptr_14standard_model_StandardModel = &__pyx_vtable_14standard_model_StandardModel;
  __pyx_vtable_14standard_model_StandardModel.init = (void *)__pyx_f_14standard_model_13StandardModel_init;
  if (PyType_Ready(&__pyx_type_14standard_model_StandardModel) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_14standard_model_StandardModel.tp_dict, __pyx_vtabptr_14standard_model_StandardModel) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "StandardModel", (PyObject *)&__pyx_type_14standard_model_StandardModel) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  __pyx_ptype_14standard_model_StandardModel = &__pyx_type_14standard_model_StandardModel;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":21 */
  __pyx_1 = __Pyx_Import(__pyx_n_sys, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_sys, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":22 */
  __pyx_1 = PyList_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  Py_INCREF(__pyx_n_array);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_array);
  __pyx_2 = __Pyx_Import(__pyx_n_array, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_array); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_array, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/james/work/py_rp/rp/standard_model.pyx":132 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("standard_model");
}

static char *__pyx_filenames[] = {
  "standard_model.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static PyObject *__Pyx_GetExcValue(void) {
    PyObject *type = 0, *value = 0, *tb = 0;
    PyObject *result = 0;
    PyThreadState *tstate = PyThreadState_Get();
    PyErr_Fetch(&type, &value, &tb);
    PyErr_NormalizeException(&type, &value, &tb);
    if (PyErr_Occurred())
        goto bad;
    if (!value) {
        value = Py_None;
        Py_INCREF(value);
    }
    Py_XDECREF(tstate->exc_type);
    Py_XDECREF(tstate->exc_value);
    Py_XDECREF(tstate->exc_traceback);
    tstate->exc_type = type;
    tstate->exc_value = value;
    tstate->exc_traceback = tb;
    result = value;
    Py_XINCREF(result);
    type = 0;
    value = 0;
    tb = 0;
bad:
    Py_XDECREF(type);
    Py_XDECREF(value);
    Py_XDECREF(tb);
    return result;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx__vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
