/* Generated by Pyrex 0.9.8.5 on Tue Feb 17 11:10:51 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "standard_core.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__Pyx_GetItemInt(PyObject *o, Py_ssize_t i); /*proto*/

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[],     Py_ssize_t nargs, PyObject **args2, PyObject **kwds2, char rqd_kwds[]); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from rp.models.standard */


/* Declarations from implementation of rp.models.standard */

struct __pyx_obj_2rp_6models_8standard_StandardModel {
  PyObject_HEAD
  struct __pyx_vtabstruct_2rp_6models_8standard_StandardModel *__pyx_vtab;
  int order;
  int radix;
  real *scores;
  int scores_len;
};


struct __pyx_vtabstruct_2rp_6models_8standard_StandardModel {
  PyObject *(*init)(struct __pyx_obj_2rp_6models_8standard_StandardModel *,int,int,real *);
};
static struct __pyx_vtabstruct_2rp_6models_8standard_StandardModel *__pyx_vtabptr_2rp_6models_8standard_StandardModel;

static PyTypeObject *__pyx_ptype_2rp_6models_8standard_StandardModel = 0;
static PyObject *__pyx_f_2rp_6models_8standard_fill_in(int,int,int **,PyObject *); /*proto*/

static char __pyx_k1[] = "array";
static char __pyx_k2[] = "d";
static char __pyx_k3[] = "append";
static char __pyx_k4[] = "typecode";
static char __pyx_k5[] = "i";
static char __pyx_k6[] = "String must be int array";
static char __pyx_k7[] = "f";
static char __pyx_k8[] = "Target must be float array";
static char __pyx_k9[] = "String and target should have same size";
static char __pyx_k10[] = "write";
static char __pyx_k11[] = "order: ";
static char __pyx_k12[] = "\n";
static char __pyx_k13[] = "radix: ";
static char __pyx_k14[] = "next";
static char __pyx_k15[] = "split";
static char __pyx_k16[] = "order:";
static char __pyx_k17[] = "Expected 'order:'";
static char __pyx_k18[] = "radix:";
static char __pyx_k19[] = "Expected 'radix:'";
static char __pyx_k20[] = "get";
static char __pyx_k21[] = "averaging";
static char __pyx_k22[] = "backoff";
static char __pyx_k23[] = "Malloc failed (counts)";
static char __pyx_k24[] = "Malloc failed (probs)";
static char __pyx_k25[] = "Malloc failed (scores)";
static char __pyx_k26[] = "sys";

static PyObject *__pyx_n_append;
static PyObject *__pyx_n_array;
static PyObject *__pyx_n_averaging;
static PyObject *__pyx_n_backoff;
static PyObject *__pyx_n_d;
static PyObject *__pyx_n_f;
static PyObject *__pyx_n_get;
static PyObject *__pyx_n_i;
static PyObject *__pyx_n_next;
static PyObject *__pyx_n_split;
static PyObject *__pyx_n_sys;
static PyObject *__pyx_n_typecode;
static PyObject *__pyx_n_write;

static PyObject *__pyx_k6p;
static PyObject *__pyx_k8p;
static PyObject *__pyx_k9p;
static PyObject *__pyx_k11p;
static PyObject *__pyx_k12p;
static PyObject *__pyx_k13p;
static PyObject *__pyx_k16p;
static PyObject *__pyx_k17p;
static PyObject *__pyx_k18p;
static PyObject *__pyx_k19p;
static PyObject *__pyx_k23p;
static PyObject *__pyx_k24p;
static PyObject *__pyx_k25p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_append, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_array, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_averaging, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n_backoff, 1, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_n_d, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_f, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_get, 1, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_n_i, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_next, 1, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_n_split, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n_sys, 1, __pyx_k26, sizeof(__pyx_k26)},
  {&__pyx_n_typecode, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_write, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k6p, 0, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k8p, 0, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k9p, 0, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k11p, 0, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k12p, 0, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k13p, 0, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_k16p, 0, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_k17p, 0, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_k18p, 0, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_k19p, 0, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_k23p, 0, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_k24p, 0, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_k25p, 0, __pyx_k25, sizeof(__pyx_k25)},
  {0, 0, 0, 0}
};

static int __pyx_d1;
static int __pyx_d2;


/* Implementation of rp.models.standard */

static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_init(struct __pyx_obj_2rp_6models_8standard_StandardModel *__pyx_v_self,int __pyx_v_order,int __pyx_v_radix,real *__pyx_v_scores) {
  PyObject *__pyx_r;
  Py_INCREF(__pyx_v_self);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":30 */
  __pyx_v_self->order = __pyx_v_order;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":31 */
  __pyx_v_self->radix = __pyx_v_radix;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":32 */
  __pyx_v_self->scores = __pyx_v_scores;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":33 */
  __pyx_v_self->scores_len = ((int)pow(((float)__pyx_v_radix), (__pyx_v_order + 1)));

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_get_order(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_get_order(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->order); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("rp.models.standard.StandardModel.get_order");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_get_radix(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_get_radix(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->radix); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("rp.models.standard.StandardModel.get_radix");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_get_scores(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_get_scores(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_a;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  long __pyx_4;
  int __pyx_5;
  Py_ssize_t __pyx_6;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_a = Py_None; Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":42 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_array); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  Py_INCREF(__pyx_n_d);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_n_d);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_a);
  __pyx_v_a = __pyx_3;
  __pyx_3 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":43 */
  __pyx_5 = ((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->scores_len;
  for (__pyx_4 = 0; __pyx_4 < __pyx_5; ++__pyx_4) {
    __pyx_1 = PyInt_FromLong(__pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_1;
    __pyx_1 = 0;
    __pyx_2 = PyObject_GetAttr(__pyx_v_a, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    __pyx_6 = PyInt_AsSsize_t(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    __pyx_3 = PyFloat_FromDouble((((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->scores[__pyx_6])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":45 */
  Py_INCREF(__pyx_v_a);
  __pyx_r = __pyx_v_a;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("rp.models.standard.StandardModel.get_scores");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_a);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_score(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_score(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_string = 0;
  int __pyx_v_start;
  int __pyx_v_length;
  int *__pyx_v_buf;
  int __pyx_v_buf_len;
  real __pyx_v_rval;
  PyObject *__pyx_r;
  int __pyx_1;
  bool __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"string","start","length",0};
  __pyx_v_start = __pyx_d1;
  __pyx_v_length = __pyx_d2;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|ii", __pyx_argnames, &__pyx_v_string, &__pyx_v_start, &__pyx_v_length)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_string);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":51 */
  __pyx_1 = PyObject_AsReadBuffer(__pyx_v_string,((void **)(&__pyx_v_buf)),(&__pyx_v_buf_len)); if (__pyx_1 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":52 */
  __pyx_v_buf_len = (__pyx_v_buf_len / (sizeof(int)));

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":53 */
  __pyx_1 = (__pyx_v_length < 0);
  if (__pyx_1) {
    __pyx_v_length = __pyx_v_buf_len;
    goto __pyx_L2;
  }
  /*else*/ {
    #ifndef PYREX_WITHOUT_ASSERTIONS
    if (!((__pyx_v_start + __pyx_v_length) <= __pyx_v_buf_len)) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    }
    #endif
  }
  __pyx_L2:;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":57 */
  __pyx_2 = score_string(((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->order,((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->radix,((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->scores,__pyx_v_buf,__pyx_v_start,__pyx_v_length,(&__pyx_v_rval));
  if (__pyx_2) {
    __pyx_3 = PyFloat_FromDouble(__pyx_v_rval); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  /*else*/ {
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("rp.models.standard.StandardModel.score");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_string);
  return __pyx_r;
}

static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_score_positions(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_score_positions(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_string = 0;
  PyObject *__pyx_v_target = 0;
  int *__pyx_v_buf;
  float *__pyx_v_t_buf;
  int __pyx_v_buf_len;
  int __pyx_v_t_buf_len;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  static char *__pyx_argnames[] = {"string","target",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_string, &__pyx_v_target)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_string);
  Py_INCREF(__pyx_v_target);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":63 */
  #ifndef PYREX_WITHOUT_ASSERTIONS
  __pyx_1 = PyObject_GetAttr(__pyx_v_string, __pyx_n_typecode); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_Cmp(__pyx_2, __pyx_n_i, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  __pyx_3 = __pyx_3 == 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (!__pyx_3) {
    PyErr_SetObject(PyExc_AssertionError, __pyx_k6p);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  }
  #endif

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":64 */
  #ifndef PYREX_WITHOUT_ASSERTIONS
  __pyx_1 = PyObject_GetAttr(__pyx_v_target, __pyx_n_typecode); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_Cmp(__pyx_2, __pyx_n_f, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
  __pyx_3 = __pyx_3 == 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (!__pyx_3) {
    PyErr_SetObject(PyExc_AssertionError, __pyx_k8p);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
  }
  #endif

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":68 */
  __pyx_3 = PyObject_AsReadBuffer(__pyx_v_string,((void **)(&__pyx_v_buf)),(&__pyx_v_buf_len)); if (__pyx_3 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":69 */
  __pyx_v_buf_len = (__pyx_v_buf_len / (sizeof(int)));

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":70 */
  __pyx_3 = PyObject_AsWriteBuffer(__pyx_v_target,((void **)(&__pyx_v_t_buf)),(&__pyx_v_t_buf_len)); if (__pyx_3 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":71 */
  __pyx_v_t_buf_len = (__pyx_v_t_buf_len / (sizeof(float)));

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":72 */
  #ifndef PYREX_WITHOUT_ASSERTIONS
  if (!(__pyx_v_buf_len == __pyx_v_t_buf_len)) {
    PyErr_SetObject(PyExc_AssertionError, __pyx_k9p);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  }
  #endif

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":73 */
  score_string_positions(((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->order,((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->radix,((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->scores,__pyx_v_buf,__pyx_v_t_buf,0,__pyx_v_buf_len);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("rp.models.standard.StandardModel.score_positions");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_string);
  Py_DECREF(__pyx_v_target);
  return __pyx_r;
}

static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_to_file(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_2rp_6models_8standard_13StandardModel_to_file(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_file = 0;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  long __pyx_4;
  int __pyx_5;
  Py_ssize_t __pyx_6;
  static char *__pyx_argnames[] = {"file",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_file)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_file);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":76 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_file, __pyx_n_write); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->order); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(((PyObject *)(&PyString_Type)), __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyNumber_Add(__pyx_k11p, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyNumber_Add(__pyx_3, __pyx_k12p); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":77 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_file, __pyx_n_write); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->radix); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(((PyObject *)(&PyString_Type)), __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyNumber_Add(__pyx_k13p, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyNumber_Add(__pyx_2, __pyx_k12p); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":78 */
  __pyx_5 = ((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->scores_len;
  for (__pyx_4 = 0; __pyx_4 < __pyx_5; ++__pyx_4) {
    __pyx_1 = PyInt_FromLong(__pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_1;
    __pyx_1 = 0;
    __pyx_2 = PyObject_GetAttr(__pyx_v_file, __pyx_n_write); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
    __pyx_6 = PyInt_AsSsize_t(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
    __pyx_3 = PyFloat_FromDouble((((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->scores[__pyx_6])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyObject_CallObject(((PyObject *)(&PyString_Type)), __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyNumber_Add(__pyx_3, __pyx_k12p); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
    __pyx_1 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("rp.models.standard.StandardModel.to_file");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_file);
  return __pyx_r;
}

static void __pyx_f_2rp_6models_8standard_13StandardModel___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_2rp_6models_8standard_13StandardModel___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);
  free_scores(((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_v_self)->scores);

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_2rp_6models_8standard_from_file(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_2rp_6models_8standard_from_file(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_f = 0;
  int __pyx_v_order;
  int __pyx_v_size;
  int __pyx_v_radix;
  real *__pyx_v_scores;
  struct __pyx_obj_2rp_6models_8standard_StandardModel *__pyx_v_rval;
  PyObject *__pyx_v_fields;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  long __pyx_5;
  real __pyx_6;
  Py_ssize_t __pyx_7;
  static char *__pyx_argnames[] = {"f",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_f)) return 0;
  Py_INCREF(__pyx_v_f);
  __pyx_v_rval = ((struct __pyx_obj_2rp_6models_8standard_StandardModel *)Py_None); Py_INCREF(Py_None);
  __pyx_v_fields = Py_None; Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":91 */
  /*try:*/ {

    /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":92 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_f, __pyx_n_next); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L2;}
    __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_split); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L2;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_v_fields);
    __pyx_v_fields = __pyx_2;
    __pyx_2 = 0;

    /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":93 */
    #ifndef PYREX_WITHOUT_ASSERTIONS
    __pyx_1 = __Pyx_GetItemInt(__pyx_v_fields, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L2;}
    if (PyObject_Cmp(__pyx_1, __pyx_k16p, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L2;}
    __pyx_3 = __pyx_3 == 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (!__pyx_3) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L2;}
    }
    #endif

    /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":94 */
    __pyx_2 = __Pyx_GetItemInt(__pyx_v_fields, 1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L2;}
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L2;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(((PyObject *)(&PyInt_Type)), __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_3 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L2;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_order = __pyx_3;
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":95 */
  /*except:*/ {
    __Pyx_AddTraceback("rp.models.standard.from_file");
    if (__Pyx_GetException(&__pyx_1, &__pyx_2, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    __Pyx_Raise(__pyx_k17p, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":98 */
  /*try:*/ {

    /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":99 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_f, __pyx_n_next); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L4;}
    __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L4;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_4 = PyObject_GetAttr(__pyx_2, __pyx_n_split); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L4;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_4, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L4;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_v_fields);
    __pyx_v_fields = __pyx_1;
    __pyx_1 = 0;

    /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":100 */
    #ifndef PYREX_WITHOUT_ASSERTIONS
    __pyx_2 = __Pyx_GetItemInt(__pyx_v_fields, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L4;}
    if (PyObject_Cmp(__pyx_2, __pyx_k18p, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L4;}
    __pyx_3 = __pyx_3 == 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (!__pyx_3) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L4;}
    }
    #endif

    /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":101 */
    __pyx_4 = __Pyx_GetItemInt(__pyx_v_fields, 1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L4;}
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L4;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_4);
    __pyx_4 = 0;
    __pyx_2 = PyObject_CallObject(((PyObject *)(&PyInt_Type)), __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L4;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_3 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L4;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_radix = __pyx_3;
  }
  goto __pyx_L5;
  __pyx_L4:;
  Py_XDECREF(__pyx_4); __pyx_4 = 0;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":102 */
  /*except:*/ {
    __Pyx_AddTraceback("rp.models.standard.from_file");
    if (__Pyx_GetException(&__pyx_4, &__pyx_1, &__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    __Pyx_Raise(__pyx_k19p, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":105 */
  __pyx_v_size = ((int)pow(((float)__pyx_v_radix), (__pyx_v_order + 1)));

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":106 */
  __pyx_v_scores = new_real_array(__pyx_v_size);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":107 */
  for (__pyx_5 = 0; __pyx_5 < __pyx_v_size; ++__pyx_5) {
    __pyx_4 = PyInt_FromLong(__pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_4;
    __pyx_4 = 0;
    __pyx_1 = PyObject_GetAttr(__pyx_v_f, __pyx_n_next); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_1 = PyObject_CallObject(((PyObject *)(&PyFloat_Type)), __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_6 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_7 = PyInt_AsSsize_t(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    (__pyx_v_scores[__pyx_7]) = __pyx_6;
  }

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":110 */
  __pyx_2 = PyObject_CallObject(((PyObject *)__pyx_ptype_2rp_6models_8standard_StandardModel), 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_rval));
  __pyx_v_rval = ((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_2);
  __pyx_2 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":111 */
  __pyx_4 = ((struct __pyx_vtabstruct_2rp_6models_8standard_StandardModel *)__pyx_v_rval->__pyx_vtab)->init(__pyx_v_rval,__pyx_v_order,__pyx_v_radix,__pyx_v_scores); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":112 */
  Py_INCREF(((PyObject *)__pyx_v_rval));
  __pyx_r = ((PyObject *)__pyx_v_rval);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("rp.models.standard.from_file");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rval);
  Py_DECREF(__pyx_v_fields);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_f);
  return __pyx_r;
}

static PyObject *__pyx_f_2rp_6models_8standard_train(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_2rp_6models_8standard_train(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_order;
  int __pyx_v_radix;
  PyObject *__pyx_v_pos_strings = 0;
  PyObject *__pyx_v_neg_strings = 0;
  PyObject *__pyx_v_kwargs = 0;
  int **__pyx_v_pos_counts;
  int **__pyx_v_neg_counts;
  real **__pyx_v_pos_probs;
  real **__pyx_v_neg_probs;
  real *__pyx_v_scores;
  struct __pyx_obj_2rp_6models_8standard_StandardModel *__pyx_v_rval;
  PyObject *__pyx_v_averaging;
  PyObject *__pyx_v_backoff;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  bool __pyx_5;
  bool __pyx_6;
  static char *__pyx_argnames[] = {"order","radix","pos_strings","neg_strings",0};
  if (__Pyx_GetStarArgs(&__pyx_args, &__pyx_kwds, __pyx_argnames, 4, 0, &__pyx_v_kwargs, 0) < 0) return 0;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "iiOO", __pyx_argnames, &__pyx_v_order, &__pyx_v_radix, &__pyx_v_pos_strings, &__pyx_v_neg_strings)) {
    Py_XDECREF(__pyx_args);
    Py_XDECREF(__pyx_kwds);
    Py_XDECREF(__pyx_v_kwargs);
    return 0;
  }
  Py_INCREF(__pyx_v_pos_strings);
  Py_INCREF(__pyx_v_neg_strings);
  __pyx_v_rval = ((struct __pyx_obj_2rp_6models_8standard_StandardModel *)Py_None); Py_INCREF(Py_None);
  __pyx_v_averaging = Py_None; Py_INCREF(Py_None);
  __pyx_v_backoff = Py_None; Py_INCREF(Py_None);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":126 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_kwargs, __pyx_n_get); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_INCREF(__pyx_n_averaging);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_averaging);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_3 = PyObject_CallObject(((PyObject *)(&PyInt_Type)), __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_averaging);
  __pyx_v_averaging = __pyx_3;
  __pyx_3 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":127 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_kwargs, __pyx_n_get); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_INCREF(__pyx_n_backoff);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_backoff);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_3 = PyObject_CallObject(((PyObject *)(&PyInt_Type)), __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_backoff);
  __pyx_v_backoff = __pyx_3;
  __pyx_3 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":129 */
  __pyx_v_pos_counts = new_counts(__pyx_v_order,__pyx_v_radix);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":130 */
  __pyx_v_neg_counts = new_counts(__pyx_v_order,__pyx_v_radix);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":132 */
  __pyx_4 = (__pyx_v_pos_counts == NULL);
  if (!__pyx_4) {
    __pyx_4 = (__pyx_v_neg_counts == NULL);
  }
  if (__pyx_4) {
    __Pyx_Raise(__pyx_k23p, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":135 */
  __pyx_1 = __pyx_f_2rp_6models_8standard_fill_in(__pyx_v_order,__pyx_v_radix,__pyx_v_pos_counts,__pyx_v_pos_strings); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":136 */
  __pyx_2 = __pyx_f_2rp_6models_8standard_fill_in(__pyx_v_order,__pyx_v_radix,__pyx_v_neg_counts,__pyx_v_neg_strings); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":138 */
  __pyx_5 = PyInt_AsLong(__pyx_v_averaging); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  __pyx_6 = PyInt_AsLong(__pyx_v_backoff); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  __pyx_v_pos_probs = counts_to_probs(__pyx_v_order,__pyx_v_radix,__pyx_v_pos_counts,__pyx_5,__pyx_6);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":139 */
  __pyx_5 = PyInt_AsLong(__pyx_v_averaging); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  __pyx_6 = PyInt_AsLong(__pyx_v_backoff); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  __pyx_v_neg_probs = counts_to_probs(__pyx_v_order,__pyx_v_radix,__pyx_v_neg_counts,__pyx_5,__pyx_6);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":141 */
  __pyx_4 = (__pyx_v_pos_counts == NULL);
  if (!__pyx_4) {
    __pyx_4 = (__pyx_v_neg_counts == NULL);
  }
  if (__pyx_4) {
    __Pyx_Raise(__pyx_k24p, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":144 */
  free_counts(__pyx_v_pos_counts,__pyx_v_order);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":145 */
  free_counts(__pyx_v_neg_counts,__pyx_v_order);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":147 */
  __pyx_5 = PyInt_AsLong(__pyx_v_averaging); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_v_scores = probs_to_score_matrix(__pyx_v_order,__pyx_v_radix,__pyx_v_pos_probs,__pyx_v_neg_probs,__pyx_5);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":150 */
  __pyx_4 = (__pyx_v_scores == NULL);
  if (__pyx_4) {
    __Pyx_Raise(__pyx_k25p, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":153 */
  free_probs(__pyx_v_pos_probs,__pyx_v_order);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":154 */
  free_probs(__pyx_v_neg_probs,__pyx_v_order);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":156 */
  __pyx_3 = PyObject_CallObject(((PyObject *)__pyx_ptype_2rp_6models_8standard_StandardModel), 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_rval));
  __pyx_v_rval = ((struct __pyx_obj_2rp_6models_8standard_StandardModel *)__pyx_3);
  __pyx_3 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":157 */
  __pyx_1 = ((struct __pyx_vtabstruct_2rp_6models_8standard_StandardModel *)__pyx_v_rval->__pyx_vtab)->init(__pyx_v_rval,__pyx_v_order,__pyx_v_radix,__pyx_v_scores); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 157; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":159 */
  Py_INCREF(((PyObject *)__pyx_v_rval));
  __pyx_r = ((PyObject *)__pyx_v_rval);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("rp.models.standard.train");
  __pyx_r = 0;
  __pyx_L0:;
  Py_XDECREF(__pyx_v_kwargs);
  Py_DECREF(__pyx_v_rval);
  Py_DECREF(__pyx_v_averaging);
  Py_DECREF(__pyx_v_backoff);
  Py_DECREF(__pyx_v_pos_strings);
  Py_DECREF(__pyx_v_neg_strings);
  Py_XDECREF(__pyx_args);
  Py_XDECREF(__pyx_kwds);
  return __pyx_r;
}

static PyObject *__pyx_f_2rp_6models_8standard_fill_in(int __pyx_v_order,int __pyx_v_radix,int **__pyx_v_counts,PyObject *__pyx_v_strings) {
  int *__pyx_v_buf;
  int __pyx_v_buf_len;
  PyObject *__pyx_v_string;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  Py_INCREF(__pyx_v_strings);
  __pyx_v_string = Py_None; Py_INCREF(Py_None);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":164 */
  __pyx_1 = PyObject_GetIter(__pyx_v_strings); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  for (;;) {
    __pyx_2 = PyIter_Next(__pyx_1);
    if (!__pyx_2) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_string);
    __pyx_v_string = __pyx_2;
    __pyx_2 = 0;

    /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":165 */
    __pyx_3 = PyObject_AsReadBuffer(__pyx_v_string,((void **)(&__pyx_v_buf)),(&__pyx_v_buf_len)); if (__pyx_3 == (-1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 165; goto __pyx_L1;}

    /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":166 */
    fill_in_counts(__pyx_v_order,__pyx_v_radix,__pyx_v_counts,__pyx_v_buf,(__pyx_v_buf_len / (sizeof(int))));
  }
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("rp.models.standard.fill_in");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_string);
  Py_DECREF(__pyx_v_strings);
  return __pyx_r;
}
static struct __pyx_vtabstruct_2rp_6models_8standard_StandardModel __pyx_vtable_2rp_6models_8standard_StandardModel;

static PyObject *__pyx_tp_new_2rp_6models_8standard_StandardModel(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_2rp_6models_8standard_StandardModel *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_2rp_6models_8standard_StandardModel *)o);
  *(struct __pyx_vtabstruct_2rp_6models_8standard_StandardModel **)&p->__pyx_vtab = __pyx_vtabptr_2rp_6models_8standard_StandardModel;
  return o;
}

static void __pyx_tp_dealloc_2rp_6models_8standard_StandardModel(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_2rp_6models_8standard_13StandardModel___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_2rp_6models_8standard_StandardModel[] = {
  {"get_order", (PyCFunction)__pyx_f_2rp_6models_8standard_13StandardModel_get_order, METH_VARARGS|METH_KEYWORDS, 0},
  {"get_radix", (PyCFunction)__pyx_f_2rp_6models_8standard_13StandardModel_get_radix, METH_VARARGS|METH_KEYWORDS, 0},
  {"get_scores", (PyCFunction)__pyx_f_2rp_6models_8standard_13StandardModel_get_scores, METH_VARARGS|METH_KEYWORDS, 0},
  {"score", (PyCFunction)__pyx_f_2rp_6models_8standard_13StandardModel_score, METH_VARARGS|METH_KEYWORDS, 0},
  {"score_positions", (PyCFunction)__pyx_f_2rp_6models_8standard_13StandardModel_score_positions, METH_VARARGS|METH_KEYWORDS, 0},
  {"to_file", (PyCFunction)__pyx_f_2rp_6models_8standard_13StandardModel_to_file, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_StandardModel = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_StandardModel = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_StandardModel = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_StandardModel = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_2rp_6models_8standard_StandardModel = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "rp.models.standard.StandardModel", /*tp_name*/
  sizeof(struct __pyx_obj_2rp_6models_8standard_StandardModel), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_2rp_6models_8standard_StandardModel, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_StandardModel, /*tp_as_number*/
  &__pyx_tp_as_sequence_StandardModel, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_StandardModel, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_StandardModel, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_2rp_6models_8standard_StandardModel, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_2rp_6models_8standard_StandardModel, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"from_file", (PyCFunction)__pyx_f_2rp_6models_8standard_from_file, METH_VARARGS|METH_KEYWORDS, 0},
  {"train", (PyCFunction)__pyx_f_2rp_6models_8standard_train, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initstandard(void); /*proto*/
PyMODINIT_FUNC initstandard(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("standard", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_vtabptr_2rp_6models_8standard_StandardModel = &__pyx_vtable_2rp_6models_8standard_StandardModel;
  *(void(**)(void))&__pyx_vtable_2rp_6models_8standard_StandardModel.init = (void(*)(void))__pyx_f_2rp_6models_8standard_13StandardModel_init;
  if (PyType_Ready(&__pyx_type_2rp_6models_8standard_StandardModel) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_2rp_6models_8standard_StandardModel.tp_dict, __pyx_vtabptr_2rp_6models_8standard_StandardModel) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "StandardModel", (PyObject *)&__pyx_type_2rp_6models_8standard_StandardModel) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  __pyx_ptype_2rp_6models_8standard_StandardModel = &__pyx_type_2rp_6models_8standard_StandardModel;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":20 */
  __pyx_1 = __Pyx_Import(__pyx_n_sys, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_sys, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":21 */
  __pyx_1 = PyList_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_INCREF(__pyx_n_array);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_array);
  __pyx_2 = __Pyx_Import(__pyx_n_array, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_array); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_array, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":47 */
  __pyx_d1 = 0;
  __pyx_d2 = (-1);

  /* "/Users/james/projects/esperr/trunk/esperr-main/rp/models/standard.pyx":161 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("rp.models.standard");
}

static char *__pyx_filenames[] = {
  "standard.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static PyObject *__Pyx_GetItemInt(PyObject *o, Py_ssize_t i) {
    PyTypeObject *t = o->ob_type;
    PyObject *r;
    if (t->tp_as_sequence && t->tp_as_sequence->sq_item)
        r = PySequence_GetItem(o, i);
    else {
        PyObject *j = PyInt_FromLong(i);
        if (!j)
            return 0;
        r = PyObject_GetItem(o, j);
        Py_DECREF(j);
    }
    return r;
}

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb) {
    PyThreadState *tstate = PyThreadState_Get();
    PyErr_Fetch(type, value, tb);
    PyErr_NormalizeException(type, value, tb);
    if (PyErr_Occurred())
        goto bad;
    Py_INCREF(*type);
    Py_INCREF(*value);
    Py_INCREF(*tb);
    Py_XDECREF(tstate->exc_type);
    Py_XDECREF(tstate->exc_value);
    Py_XDECREF(tstate->exc_traceback);
    tstate->exc_type = *type;
    tstate->exc_value = *value;
    tstate->exc_traceback = *tb;
    return 0;
bad:
    Py_XDECREF(*type);
    Py_XDECREF(*value);
    Py_XDECREF(*tb);
    return -1;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_GetStarArgs(
    PyObject **args, 
    PyObject **kwds,
    char *kwd_list[], 
    Py_ssize_t nargs,
    PyObject **args2, 
    PyObject **kwds2,
    char rqd_kwds[])
{
    PyObject *x = 0, *args1 = 0, *kwds1 = 0;
    int i;
    char **p;
    
    if (args2)
        *args2 = 0;
    if (kwds2)
        *kwds2 = 0;
    
    if (args2) {
        args1 = PyTuple_GetSlice(*args, 0, nargs);
        if (!args1)
            goto bad;
        *args2 = PyTuple_GetSlice(*args, nargs, PyTuple_GET_SIZE(*args));
        if (!*args2)
            goto bad;
    }
    else if (PyTuple_GET_SIZE(*args) > nargs) {
        int m = nargs;
        int n = PyTuple_GET_SIZE(*args);
        PyErr_Format(PyExc_TypeError,
            "function takes at most %d positional arguments (%d given)",
                m, n);
        goto bad;
    }
    else {
        args1 = *args;
        Py_INCREF(args1);
    }
    
    if (rqd_kwds && !*kwds)
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i])
                    goto missing_kwarg;
    
    if (kwds2) {
        if (*kwds) {
            kwds1 = PyDict_New();
            if (!kwds1)
                goto bad;
            *kwds2 = PyDict_Copy(*kwds);
            if (!*kwds2)
                goto bad;
            for (i = 0, p = kwd_list; *p; i++, p++) {
                x = PyDict_GetItemString(*kwds, *p);
                if (x) {
                    if (PyDict_SetItemString(kwds1, *p, x) < 0)
                        goto bad;
                    if (PyDict_DelItemString(*kwds2, *p) < 0)
                        goto bad;
                }
                else if (rqd_kwds && rqd_kwds[i])
                    goto missing_kwarg;
            }
        }
        else {
            *kwds2 = PyDict_New();
            if (!*kwds2)
                goto bad;
        }
    }
    else {
        kwds1 = *kwds;
        Py_XINCREF(kwds1);
        if (rqd_kwds && *kwds)
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i] && !PyDict_GetItemString(*kwds, *p))
                        goto missing_kwarg;
    }
    
    *args = args1;
    *kwds = kwds1;
    return 0;
missing_kwarg:
    PyErr_Format(PyExc_TypeError,
        "required keyword argument '%s' is missing", *p);
bad:
    Py_XDECREF(args1);
    Py_XDECREF(kwds1);
    if (args2) {
        Py_XDECREF(*args2);
    }
    if (kwds2) {
        Py_XDECREF(*kwds2);
    }
    return -1;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
